export const EXPENSE_FETCH_SUCCESS = 'EXPENSE_FETCH_SUCCESS';
export const EXPENSE_FETCH_FAIL = 'EXPENSE_FETCH_FAIL';
export const EXPENSE_FETCH = 'EXPENSE_FETCH';
export const INTERNET_CONNECTION_FAIL = 'INTERNET_CONNECTION_FAIL';