export const LEDGER_FETCH_SUCCESS = 'LEDGER_FETCH_SUCCESS';
export const LEDGER_FETCH_FAIL = 'LEDGER_FETCH_FAIL';
export const LEDGER_FETCH = 'LEDGER_FETCH';
export const INTERNET_CONNECTION_FAIL = 'INTERNET_CONNECTION_FAIL';
export const LOADING_CHANGE = 'LOADING_CHANGE';